### ISSUE TITLE
Url cannot be reached

### ISSUE THREAD

**Issue by laravelish** [spatie/laravel-medialibrary#1010]
Hi, how to deal with url cannot be reached ? but i can reach it using the browser or download manager

url example `https://s295.**.com/newdl/_Dfh_sI_3jUlwpAYRLl90Q/1522117054/0/1619800/1619800_1920x1080_4000k.mp4`

**Comment by freekmurze** [comment]
Which error are you getting?

Feel free to PR a failing test.

**Comment by laravelish** [comment]
Sorry this can be closed because the url is generated based on user ip or something like that i think

**Comment by mydnic** [comment]
I have the same issue on my local environment, really weird. On my test server it's working fine. Is it possible that the method `addMediaFromUrl()` is checking if the **Media URL is accessible from the internet ??**
cc @freekmurze

**Comment by mydnic** [comment]
Nevermind, I found the problem:

For some reason, it's not working if using HTTPS in local development with Laravel Valet.

I "unsecured" my local site and now it's working fine

```bash
$ art tinker
Psy Shell v0.9.9 (PHP 7.2.9 — cli) by Justin Hileman
>>> @fopen('https://fitnss.test/assets/uploads/yrRPzaw1X4Is2VctOofgw8Q5T2ZIlCMJoYYSHqCO.jpeg', 'r')
PHP Warning:  fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in Psy Shell code on line 1
PHP Warning:  fopen(): Failed to enable crypto in Psy Shell code on line 1
PHP Warning:  fopen(https://fitnss.test/assets/uploads/yrRPzaw1X4Is2VctOofgw8Q5T2ZIlCMJoYYSHqCO.jpeg): failed to open stream: operation failed in Psy Shell code on line1
=> false
>>>

$ valet unsecure fitnss
Password:
Restarting php...
Restarting nginx...
The [fitnss.test] site will now serve traffic over HTTP.

$ art tinker
Psy Shell v0.9.9 (PHP 7.2.9 — cli) by Justin Hileman
>>> @fopen('http://fitnss.test/assets/uploads/yrRPzaw1X4Is2VctOofgw8Q5T2ZIlCMJoYYSHqCO.jpeg', 'r')
=> stream resource #806
```

**Comment by ahmedsayedabdelsalam** [comment]
I have the same problem I think it is related to https when using valet may be due to an invalid certificate or something

I replaced addMediaFromUrl() method with addMedia() because I want to access file which already exists local in the project

`$model->addMedia(public_path('path-to-image'))->preservingOriginal()->toMediaCollection('collection-name');`

I hope it works with you.

**Comment by mowses** [comment]
Sorry for commenting this issue as it is closed already. But I realized a weird behavior in media library. I dont know if its a bug or what.
Here is the case:

When displaying images, if you just call `getFirstMediaUrl()` it prints something like this:
`http://bettina.localhost/storage/6/cover_img.jpg` which works OK. But the media library uses env's `APP_URL` to generate the final url. You may test it in your local environment, just change it value in your env file.
In most cases this aproach works fine.

But the issue arises when I try to load the page from another device in my local network. I am using a mobile phone to navigate through the site, but the images did not load. Since the host name `http://bettina.localhost` cant be located from my phone because I am accessing the page via `http://192.168.1.3`.

This problem can be solved if your library would use laravel's `url()` to generate the url to the image.
In my page, there are some images that is not using the library and the images are loaded because `url()` translates the domain `http://bettina.localhost` to the domain the client is accessing (the same in the address bar).

I would like to hear your comments about this issue. Does it happen to you too?
Meanwhile a need to make a wrapper for the `getFirstMediaUrl` method to deal with this kind of bug.

**Comment by mowses** [comment]
I managed to deal with my issue. I modified the config file:
`config/filesystems.php`

changed `disks.public.url` from `env('APP_URL').'/storage',` to `url('/storage'),`

now all images are loading :)
