### ISSUE TITLE
Add a method to Media to check if a thumbnail exists

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-medialibrary#1020]

**Comment by brendt** [comment]
Correct me if I'm wrong, but I guess you want to check whether a conversion is already rendered or not?

**Comment by sebastiandedeyne** [comment]
Use case: A `thumbnail` conversion for a collection containing different file types. This conversion would exist for a pdf file, but wouldn't for an xls file.

**Comment by omarrida** [comment]
I have a similar need for a different use-case. My existing system contains thousands of images managed by the media-library.

I recently registered a new conversion to support transparent .png images (essentially maintaining the original uploaded image with some optimizations). The problem is that now ALL my media arrays are returning the new conversion type's url, even for models which were created before I registered the conversion. I have to do ugly client-side checks to figure out which image url to load.

P.S. I know that I'm an asshole for not sending a postcard yet. Sorry Spatie, I will do it soon. Promise.

**Comment by brendt** [comment]
@sebastiandedeyne and I had a little discussion about this. Here are our thoughts:

We could add a method `hasGeneratedMediaConversion($name)` or `hasMediaConversion($name)` or something similar. This would solve a great many cases in which we now have to write a lot more conditionals in view files.

There's a problem with the implementation though.

We can do the check **at runtime**, meaning we'd check if the conversion files actually exist on the filesystem. The obvious problem here is S3 filesystems, as it means that a call to `hasMediaConversion` means a HTTP request. That's going to very inefficient.

We could keep a mapping of generated media files **on the media item** itself. This mapping means we can toggle a flag for a conversion when that conversion is generated. The problem here is backwards compatibility. We could add a new column or table, which automatically means a breaking change. Another approach could be to (mis)use the custom properties of a Media item. Seb argued about what would happen if people manually cleared custom properties in their code, which means this wouldn't work.

Even if we decided to use custom properties, it would still require all existing models to be updated with a script, before this meta data is registered in the database. I'm not sure this would count as a "breaking change" though.

@freekmurze , what's your input?

**Comment by freekmurze** [comment]
I'm thinking that we should avoid making http requests at all costs, so the check can't happen at runtime. For responsive images we're already working with the mapping @brendt described above, and  it seems like this is indeed the way to go to solve this problem.

Let's indeed use the custom properties for now to store this information. In the next major version of the package™ we'll introduce a dedicated field for this.

**Comment by brendt** [comment]
FYI the method `hasGeneratedConversion` is available as of v7.2.0

Be sure to read the UPGRADING guide for existing projects: https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md#720

**Comment by matthewgovaere** [comment]
Hmm, is there anything specific I need to do in order for the generated custom properties to show up in the database?

I'm adding the file like this...
```
$user
    ->addMedia($request->file('image'))
    ->toMediaCollection('avatar');
```

and added the conversions like this...
```
public function registerMediaCollections()
{
    $this
        ->addMediaCollection('avatar')
        ->useDisk('s3')
        ->singleFile()
        ->registerMediaConversions(function (Media $media = NULL) {
            $this
                ->addMediaConversion('small')
                ->format('jpg')
                ->fit('crop', 300, 300);

            $this
                ->addMediaConversion('medium')
                ->format('jpg')
                ->fit('crop', 500, 500);

            $this
                ->addMediaConversion('large')
                ->format('jpg')
                ->fit('crop', 1000, 1000);
        });
}
```

The `hasGeneratedConversion` method comes up as `false`, assuming because the `custom_properties` field in the database doesn't show any of the conversion data, even though the conversions are saved correctly within the file system.

**Comment by brendt** [comment]
@matthewgovaere What version of the media library are you using? Are you testing this on existing media items or new ones?

**Comment by matthewgovaere** [comment]
@brendt I'm using 7.3.8, and testing on new media items.

I did some variable dumps during the methods `markAsConversionGenerated` and `performConversions`, and noticed each conversion contains the proper `custom_properties` fields, but it appears they're never added to the `custom_properties` for the original media item that actually gets saved to the database.

**Comment by brendt** [comment]
Thanks for digging into this. Feel free to open an issue and even submit a fix PR if you're willing.

**Comment by adam1920** [comment]
getAvailablePath function solve this problem.
From here `vendor/spatie/laravel-medialibrary/src/MediaCollections/Models/Media.php`

```
public function getAvailablePath(array $conversionNames): string
    {
        foreach ($conversionNames as $conversionName) {
            if (! $this->hasGeneratedConversion($conversionName)) {
                continue;
            }

            return $this->getPath($conversionName);
        }

        return $this->getPath();
    }
```
