### ISSUE TITLE
rmdir(/tmp): Permission denied

### ISSUE THREAD

**Issue by taliptako** [spatie/laravel-medialibrary#1030]
I'm just trying to add pictures to my model 
Here is the stack trace 
[https://kopy.io/0ogR9#ddi8F0d8E7U2GH](https://kopy.io/2LuPT#ocVm8w6MQCTKXg)

**Comment by brendt** [comment]
Unfortunately, this is a know issue: https://github.com/spatie/laravel-medialibrary/issues/887. The underlying issue is here: https://github.com/spatie/image/issues/38

I'd recommend reading through that thread to know what's going on. I'll try to look at a fix this week, though we first need a consensus on how to fix it.
