### ISSUE TITLE
image compression

### ISSUE THREAD

**Issue by erikbelusic** [spatie/laravel-medialibrary#105]
is there a way to compress/optimize images with this package?

some of the uploaded images, even after being resized, are reported that they could be optimized further, some up to 80%.

if this is not a feature, is there some package that you are aware of that can be used in conjunction?

thanks!

**Comment by huglester** [comment]
Hello,

if I understand correct, you are refering to google insights, or google mobile check or something like that.

Image optimization/compression/cleaning (lossless maybe) is a 'heavy' work, 1 image optimization (I believe) could be from 1 up to 5 seconds or so. SOme GO packages may do it a lot faster than php (maybe even in lossless mode), but this one probably requires some 'post processing', usually done by queues or osmething like that.

Because otherwise if user first visits the page, an images will need to be generated/optimized (ie. 10 images) it would hand for a minute.

But it's a good idea/call - maybe someone could share some libs for lossless ocmporession even in php:) I would like to see them too!

**Comment by freekmurze** [comment]
Compression functionality is not provided by this package. You should compress your files before adding them to the medialibrary.

I don't have any suggestion on which package you could use, but Google a bit and I'm pretty sure you'll find a good one.

Creating optimized images is a responsibility of Glide. If you have suggestions have Glide could create better output, it's best to add an issue there.

**Comment by freekmurze** [comment]
Will take some time to improve on this soon.

**Comment by erikbelusic** [comment]
What are you planning on doing? I've left this alone as other items became far more important in the app, and I switched companies so I'm not working on it anymore now.

When I look at how WP plugins handle this, they seem to delegate to optipng or something similar creating very high cpu usage so I'm curious what solution you have in mind?

The solution may turn out to be a separate package that can both do it locally, or use a different box, or delegate to a service that can do it in the cloud. Not sure!

**Comment by freekmurze** [comment]
The current plan is to add fire off an event right after an image is created via a conversion.  The compression will indeed be handled in a seperate package. 

I still have to research a lot before creating that new package. Maybe another one that does this already exists.

I'll work on this whenever I got a little bit of time.

**Comment by gitllermopalafox** [comment]
Hi, recently I found this site http://cloudinary.com/ (I haven't tried it yet) maybe it could help you.

**Comment by taliptako** [comment]
@freekmurze  If we compress files after the conversion we should also compress their conversions and its mean more processor load but if we do this before the conversions, conversions will also created with compressed image and its mean they will smaller like original image isnt it ?

Also maybe you can look this package https://github.com/approached/laravel-image-optimizer

**Comment by nicolasbeauvais** [comment]
Not exactly compression but you can change image quality using glide which will greatly reduce the image size (http://glide.thephpleague.com/1.0/api/encode/#quality-q)

```php
$this->addMediaConversion('small')
            ->setManipulations(['w' => 166, 'h' => 166, 'fit' => 'fill', 'q' => 80, 'fm' => 'jpg'])
            ->performOnCollections('default');
```
