### ISSUE TITLE
attaching a photo afterwards, when post id is available.

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#109]
So lets say I want to create a new post.
And I type in the title and now I want to upload the featured image.
I upload the image immediatelly via ajax. but i still dont have the post id.
Now after I fill out some basic content of the post and save it, I want to attach that image to
that post? 

Any ideas?

**Comment by freekmurze** [comment]
You must have a saved eloquent model in order to attach media to it.

[In our projects](https://github.com/spatie-custom/blender) we save an eloquent model with a draft flag. We set the draft flag to zero after the user has successfully saved for the first time.

**Comment by palypster** [comment]
@freekmurze we are looking for a solution of this same problem. We found your proposed solution mentioned couple of times in these GitHub issues (by you or your colleagues), we discussed a lot about it, but we see a problem - maybe you also addressed this issue before.

1. the problem we are dealing is, that what we need is final URL of the media before the model is saved. We are creating a meadia library for a WYSIWYG editor. Imagine you are creating a new Blogpost (the model is not saved yet). We were thinking, maybe we can create a Medium and attach it to the model later. Is there a way to do it with v7? With proposed "draft" solution has many drawbacks (i.e. use of events is harder, maybe some logging, you need to scope every query so you select only draft etc.). Don't get me wrong, we still consider it as a potential solution, we are just debating about the pros & cons and looking to hear your view.
1. second problem is more serious. Imagine you have some database constraints i.e. NOT NULL or even UNIQUE, how do you save a model as draft? Fake the data? We find it really weird and probably over the line :) How have you solved it?

We are looking for a generic solution, because we have built a package on top of your media library (we already chatted about that via email some time ago :P ).

Thank you

**Comment by palypster** [comment]
@javi-dev - you was looking into the similar problem I guess, maybe you are interested.
