### ISSUE TITLE
Preserve CMYK in media conversions?

### ISSUE THREAD

**Issue by ingageco** [spatie/laravel-medialibrary#1147]
Hello -

I recently noticed our converted images were all in RGB and not in the originally-uploaded CMYK color space. We have some simple conversions - just changing the size, so it seems this might be a default action. How can I preserve the color space when generating conversions? Here are our conversions -- thanks in advance for any help!

```
$this->addMediaConversion('thumb')->fit(Manipulations::FIT_FILL,320, 320)
->background('ffffff')
->nonQueued();


        $this->addMediaConversion('xxlarge')
        ->fit(Manipulations::FIT_CONTAIN, 2880, 2880)
        ->nonQueued();

        $this->addMediaConversion('xlarge')
        ->fit(Manipulations::FIT_CONTAIN, 1920, 1920)
        ->nonQueued();

        $this->addMediaConversion('large')
        ->fit(Manipulations::FIT_CONTAIN, 960, 960)
        ->nonQueued();
```

**Comment by DaanAmsterdam** [comment]
Hi there, I'm having a similar or the same problem.

I have everything setup and it works well. My problem is that when I generate media conversions from my original photo (width 1920) the conversions look different. The pictures have a lot less colour in it, they look a lot more pale, for instance a lot of yellow gets pulled out. It feels like the hue and saturation gets lowered.

I have used both GD and Imagick (wow, to set that up on mac!) but the problem is the same with both drivers.

I have tried to generate the images with nonOptimized like this but it doesn't make a difference for the colour changes.

please check my original post as of yesterday on Laracasts.

https://laracasts.com/discuss/channels/general-discussion/spatie-media-library-image-changes-the-colourhue-of-converted-photos

Regards, Daan

**Comment by freekmurze** [comment]
I'd accept fully tested PRs for this at this repo and the spatie/image one.

Goal is to get this code to work:

```php
 $this->addMediaConversion('large')
        ->preserveColorSpace()
        ->fit(Manipulations::FIT_CONTAIN, 960, 960)
        ->nonQueued();
```

Interesting response at Laracasts: https://laracasts.com/discuss/channels/general-discussion/spatie-media-library-image-changes-the-colourhue-of-converted-photos/replies/432794
