### ISSUE TITLE
"Only strings, FileObjects and UploadedFileObjects can be imported"

### ISSUE THREAD

**Issue by ELmardi2** [spatie/laravel-medialibrary#1219]
I could add image but i had this error

**Comment by AlexVanderbist** [comment]
Can you share the code where you're adding the image to the media library?

**Comment by adriandmitroca** [comment]
This happens when you are iterating on a set of images and trying to add the same image at the second time (for example, in seeders).

By default, Media Library deletes original file after adding it to the library. To avoid this, make sure your original files will be untouched by using this method:
https://docs.spatie.be/laravel-medialibrary/v7/api/adding-files#preserveoriginal

**Comment by Dresing** [comment]
Beware that the interface `Spatie\MediaLibrary\HasMedia` with method `media()` gets implemented by `Spatie\MediaLibrary\HasMedia\HasMediaTrait`. You may experience conflicts if you define relations with the same name yourself.

**Comment by Akhibemudu** [comment]
@adriandmitroca  Please is there a way I can upload new image[s] to an existing model? In my situation, I created a Property form that accepts multiple property images which works well, but the problem is when trying to update that Property Model to accepts more image whenever the user clicks on update form, I get the same error as above. 
Here is it for update function.
` foreach ($request->file('property_photos', []) as $key => $file) {
            $property->addMedia($file)
                ->preservingOriginal()
                ->toMediaCollection('property_image');
        }`
**For this update, I want to add more images to the existing image in the Property Model without having to delete previous uploaded image**

**Comment by thsdeveloper** [comment]
Hello, I need some help. I cannot perform this operation...

```
$base64 = "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQA..."
$img = Image::make($base64);
$user = User::find(1);
$user->addMedia($img)->preservingOriginal()->toMediaCollection('perfil');
```

**Comment by RahulMachhiC** [comment]
Same Error 
Image Store Method 
   public function store(Request $request)
    {
        $file = $request->file('image');
        $input = $request->all();
        $post = $this->create($input);

        $post->addMedia($file)->toMediaCollection();
    }

**Comment by alifsyahakbar** [comment]
> If you're still experiencing this issue: can you share the code where you're adding the image to the media library?
> 
> If not, feel free to close this issue. Thanks!

**Comment by alifsyahakbar** [comment]
please..i can't fix it
