### ISSUE TITLE
Responsive image URLs ignore s3 root

### ISSUE THREAD

**Issue by HipsterJazzbo** [spatie/laravel-medialibrary#1220]
When generating a responsive image srcset, if using the s3 driver the responsive image urls that are generated ignore the s3 'root' config, making the links broken.

**Comment by freekmurze** [comment]
There's already a fix surround the url generation of responsive images (#1195). If you need a fix quickly, feel free to open up a new PR.

**Comment by robinvalk** [comment]
After a quick look into the sourcecode, I think we need to extend the base path generator and create a new one specific for S3. We can use that one then for the S3UrlGenerator so that the root path is always included.

Second opinion appreciated, I suggest creating a separate PR for this so the PR #1195 is not on hold for S3.

**Comment by freekmurze** [comment]
Seems like this one is solved.
