### ISSUE TITLE
$media->move() raises an error if the filename has no extension

### ISSUE THREAD

**Issue by amrnn90** [spatie/laravel-medialibrary#1258]
If I try to move a media with a filename that doesn't contain an extension, I receive an error similar to the following:

`fopen(/myproject/storage/medialibrary/temp/SRzedmRMFTWXhiovt208SvevwZYiVacN/1538583003_2pMnshlcV2): failed to open stream: Is a directory in /myproject/vendor/spatie/laravel-medialibrary/src/Filesystem/Filesystem.php on line 89`

**Comment by princeton255** [comment]
Plus 1 on this. Faced same issue when trying to move user uploaded files which were missing extensions. Seems they are created in temp directory as folders instead of files.

**Comment by freekmurze** [comment]
I'd accept a PR with tests that fixes this

**Comment by VincentKos** [comment]
The problem came from the method `isFilePath` in `TemporaryDirectory`. The way you detect if the path is a file or a folder is by looking for a point, in a file without extension, chance are, you will never find it so it return false and create two folder in the `path` method (same file).

Would love to PR but i can fix it but not test it :confused:

**Comment by brendt** [comment]
@VincentKos are you still up for this? I'll be happy to help you to write some tests for this. Who knows, it might a a good learning opportunity? Feel free to submit a PR with a fix, and we can take it from there.

**Comment by VincentKos** [comment]
@brendt i'm gonna pr something soon then.
