### ISSUE TITLE
masonry grid glide image api structure?

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#126]
I need to build a masonry image grid. So some image orientation will be horizontal some will be vertical.

![masonrygrid](https://cloud.githubusercontent.com/assets/7913974/12017884/7ef08bdc-ad5c-11e5-8c6f-0693c47ef3b7.jpg)

So I am wondering what mix of the api should / could use to convert the images based on their orientation?

any ideas suggestions?

**Comment by freekmurze** [comment]
There are many ways to go about this. Because the medialibrary doesn't allow for conditional resizen, I'd resize them before adding them to the medialibrary. 
Another way could be to detect the orientation first and depending on the result add them to a collection with the conversion parameters you need.

It all depends on your specific needs.
