### ISSUE TITLE
How to get media url with model in API response

### ISSUE THREAD

**Issue by ClickerTech** [spatie/laravel-medialibrary#1262]
Hi,

I am working on am mobile app development which fetch models from API endpoints

no how i can get media url with model in API response

Thanks

**Comment by amrmsccs** [comment]
Hello, Here is sample work around since I was looking for the same answer and took me really long time to figure it out, I didn't get any quick and short example. 
Assume you have a model called Library  that is having a relationship with another model called Book and you wanna retrieve the Books with its cover photos.

`$library = Library::whereDate('published_date', '>=', $tody)->where('published', '1')->with("book")->with("created_by")->get();`

You need to Change the  **$library** collection to modify the books images to insert **link** attribute for every book image exist and retrieved.
Here is the Code where **getMedia('images')** is the collection you have saved your images in.
`$library = $Library->transform(function ($item, $key) {
                                  foreach ($item->book->getMedia('images') as $media) {
                                                 $media['link'] = $media->getFullUrl();
                                  }
                             return $item;
                        });`

return the result as json resopnse

`if($library->isEmpty()) {
            return response()->json(['data' => null]);
        }else{
            return response()->json(['data' => $trip]);
        }`

Hope this help others.

**Comment by ClickerTech** [comment]
Hi,

see my code

`

Route::get('/media', function () {
    $admin = Admin::find(1);
    $admin->addMedia(storage_path('/app/demo/test.png'))
        ->preservingOriginal()
        ->toMediaCollection('avatar');
    return $admin;
});

Route::get('1', function () {
    $admin = Admin::find(1);
    $admin = $admin->transform(function ($item, $key) {
        foreach ($item->book->getMedia('avatar') as $media) {
            $media['link'] = $media->getFullUrl();
        }
        return $item;
    });

    if ($admin->isEmpty()) {
        return response()->json(['data' => null]);
    } else {
        return response()->json(['data' => $admin]);
    }
});
`

i am getting this error

`Call to undefined method App\Models\Admin::transform()`

**Comment by ClickerTech** [comment]
hi,

i done like this is this correct way to do?

`Route::get('1', function () {
    $admin = Admin::find(1);
    $avatar = $admin->getFirstMediaUrl('avatar');
    $admin->avatar = $avatar;
    return $admin;
});`

**Comment by freekmurze** [comment]
Seems good!

**Comment by masterix21** [comment]
@freekmurze, what about an "URLs" property in the `Media` model with all URLs? It will solve the annoying transform processes using the library with the APIs.

```php
// Example
$media->urls
```

```php
// Response example
[
    'original' => 'http://example1.com/image.jpg',
    'thumb' => 'http://example1.com/image/thumb.jpg',
    'landscape' => 'http://example1.com/image/landscape.jpg',
    'portrait' => 'http://example1.com/image/portrait.jpg',
    'grayscale' => 'http://example1.com/image/grayscale.jpg',
    // ...
]
```

Implementing a mutator, at any time everybody could change the generation URLs logic, for example:
- to generate URLs only for the auth users
- to generate temporary URLs only

What do you think about it?

**Comment by freekmurze** [comment]
Thanks for the suggestion. I'm thinking this is something that should be done by the users of the package, and not by the package itself. It might be something worthy to add to the docs though.
