### ISSUE TITLE
IE11 problems: this.onload=null

### ISSUE THREAD

**Issue by zangab** [spatie/laravel-medialibrary#1321]
I use your library and it works fine except in - surprise surprise - IE11.
I render resposive images with `{{ $image('large', [ some-attributes ]) }}` and for IE I also included the `picturefill` polyfill. However, it doesn't update the image. It always shows the placeholder svg and the `sizes` attribute on the image-tag never gets updated.

So I started looking into your blade files. On the image-onload hook, i found this:
```this.onload=null;this.sizes=Math.ceil(this.getBoundingClientRect().width/window.innerWidth*100)+'vw'```.

If i delete the `this.onload=null` part, it does work on IE11 but I'm wondering what this stuff does and why it's placed there? Doesn't it reset the `onload` handler to null so the `this.sizes=...` part can not get executed at all??

Appreciate a repsonse.
Keep up the great work.

**Comment by willemvb** [comment]
https://docs.spatie.be/laravel-medialibrary/demo/responsive-images
This demo should work in IE11, does it work for you?

We don't use a polyfill ourselves and don't have actual experience with it. Since IE11 doesn't support `srcset`, things should work out of the box with the largest file available as declared in the standard `src` attribute. Kinda brute force, but it works.

In some cases (browsing back, or loading images from cache) we experienced that the unload script was executed multiple times. The `this.onload=null` is an inline technique to prevent this. The browser should however execute the entire statement the first time.
 
So I wouldn't recommend removing it, because it would deoptimize behaviour for newer browsers.
Maybe you could try switching it to the end of the line?
`this.sizes=Math.ceil(this.getBoundingClientRect().width/window.innerWidth*100)+'vw';this.onload=null`

Let me know if this helps.
