### ISSUE TITLE
(re)generate responsive images?

### ISSUE THREAD

**Issue by eminos** [spatie/laravel-medialibrary#1425]
I have a bunch of images added before adding the responsive images feature. Is there a way to generate responsive images for those?

Seems the `regenerate` command doesn't create the responsive images for the original file? (Only conversions?)

**Comment by Nevax07** [comment]
This issue seems to be at this line:
https://github.com/spatie/laravel-medialibrary/blob/089ee0784b9b539331048a5fa144d050e30711c1/src/FileManipulator.php#L104

I have a pretty **dirty** patch to make it just work, i will take a look later to refactor and for PR.

Add this code to this file.
https://github.com/spatie/laravel-medialibrary/blob/089ee0784b9b539331048a5fa144d050e30711c1/src/FileManipulator.php#L45

```php
        if ($media->hasResponsiveImages()) {
            $generateResponsiveImagesJobClass = config('medialibrary.jobs.generate_responsive_images',
                GenerateResponsiveImages::class);

            $job = new $generateResponsiveImagesJobClass($media);

            if ($customQueue = config('medialibrary.queue_name')) {
                $job->onQueue($customQueue);
            }

            dispatch($job);
        }
```

**Comment by Nevax07** [comment]
I finally found some time to work on this.
After digging the code, I can see the command only regenerate conversions and not the collection itself. So, you probably need to create a specific conversion for the responsive images.

```php
$this->addMediaConversion('conversion')
            ->withResponsiveImages()
            ->performOnCollections('collection');
```

**Comment by brendt** [comment]
You'd need to generate them yourself, I'd suggest writing a migration for it.
