### ISSUE TITLE
Multiple file extensions and picture object generation

### ISSUE THREAD

**Issue by Briareos17** [spatie/laravel-medialibrary#1461]
Hi, your package is awesome, especially responsive images, but I have one issue with ability to store images in multiple extensions, like png, webp, jpeg for browser compability.
Is there any way to manage conversions for extensions to be able create HTML5 picture object?

**Comment by freekmurze** [comment]
Thank you! Currently this is not possible. I don't have a need for this yet, so probably this won't get added in the near future.

**Comment by Stichoza** [comment]
That was two years ago, lately Google became more strict about images - it lowers your score if you do not provide webp alternatives for jpeg/png images. So for any developer who wants to improve their Google PageSpeed score, this feature is crucial.

It would be awesome if medialibrary supported multiple formats, so when defining conversions, instead of `->format('jpg')` we could also do `->format(['jpg', 'webp'])`. Or simply `->withWebpFormat()` and `->withWebpFormatIf($condition)` which will generate webp image along with jpg or whatever is defined in conversion.

Later, if we write something like `{{ $media }}` or `{{ $media('conversion-name') }}`, instead of:

```html
<img src="..." srcset="..."/>
```

it would output:

```html
<picture>
    <img source="....webp" type="image/webp"/>
    <img source="....jpg" type="image/jpeg"/>
    <img src="..." srcset="..."/><!-- default image -->
</picture>
```

**Comment by divdax** [comment]
I agree with @Stichoza. Google PageSpeed also suggests `jp2` (never heard this format before...) for Safari, so multiple formats are needed.

@freekmurze any chance to overthink this?
