### ISSUE TITLE
browsing /index.php breaks images (can be seen on spatie.be/ohdear.app)

### ISSUE THREAD

**Issue by eminos** [spatie/laravel-medialibrary#1462]
Browsing to /index.php is the same as the home route "/" in a standard Laravel installation (web server setup).
But it breaks image URLs generated by medialibrary.

The issue can also be seen on spatie.be and ohdear.app.
https://spatie.be/index.php
https://ohdear.app/index.php

In my case the issue is even worse because the home route gets cached (and re-cached) when I visit /index.php, which then breaks images on the cached normal / home route.

**Comment by AlexVanderbist** [comment]
Hi @eminos,

This seems to be an issue with Laravel's `url()` helper in combination with out webserver set-up. This simple example already gives a broken url:
```php
Route::get('test', function () {
    return url('/image.jpg');
    // will show http://example.test/index.php/image.jpg
});
```

This is probably because we are using the `url()` helper in a file context, instead of using it for routing as intended. However, this is not something we want to fix in the current version as it might break other people's setups. I'll open an issue to fix this in the next major release of medialibrary.

Thanks!
