### ISSUE TITLE
I wish to use Only allow certain files in a collection, but it not working  that is my code

### ISSUE THREAD

**Issue by danielshongo** [spatie/laravel-medialibrary#1516]
```php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\File;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements HasMedia
{
    use Notifiable, HasMediaTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function registerMediaCollections()
    {
        $this->addMediaCollection('slider')
            ->acceptsFile(function (File $file) {
                return $file->mimeType === 'image/jpeg';
            });

    }
}
```

**Comment by freekmurze** [comment]
What do you mean by "not working"?

Are you getting an exception?

Are you sure the `acceptsFile` is being called? Try to put a `dd` statement in there to be sure.

**Comment by danielshongo** [comment]
sorry i d'ont speack english verry, i love this package, tis is my problem 
when i put dd after addMediaCollection, it does stop me codes when i put in the function acceptsFile (function (File $ file) {
   return $ file-> mimeType === 'image / jpeg';
        }); I get nothing. media saves all the file. help me please I'm blocking

**Comment by danielshongo** [comment]
sorry i d'ont speack english verry, i love this package, this is my problem
when i put dd after addMediaCollection, it does stop me codes when i put in
the function acceptsFile (function (File $ file) {
add('dd');
return $ file-> mimeType === 'image / jpeg';
}); I get nothing. media saves all the file. help me please I'm blocking

**Comment by brendt** [comment]
@danielshongo I believe your issue has to do with your code not working as described in https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections/#only-allow-certain-files-in-a-collection ?

Since the tests for this on our side (https://github.com/spatie/laravel-medialibrary/blob/master/tests/Feature/FileAdder/MediaConversions/MediaCollectionTest.php#L137) still work, my suggestion would be to carefully read the docs.

If the problem persists and you're sure this is a problem within the media library, you could send a pull request with a failing test to show what goes wrong.

I'll be closing this issue for now, as I don't think this is a problem with the media library. Feel free to keep the conversation going if you need any more pointers.
