### ISSUE TITLE
Getting The "/tmp/****" file does not exist or is not readable.

### ISSUE THREAD

**Issue by hazem-taha** [spatie/laravel-medialibrary#1613]
Hello,

I'm getting the below error even if I'm uploading very small images.

![image](https://user-images.githubusercontent.com/46519001/67857785-b4acd500-fb28-11e9-8ec1-394d71935af5.png)

any solution ??

Thanks

**Comment by freekmurze** [comment]
@hazem-taha it's probably related to some permission setting in your environment. If there is something that can be done in medialibrary to fix this, send a PR.

**Comment by tiagosimoesdev** [comment]
I'm getting the same issue . Already tried in Windows, macOS and linux ..

**Comment by harryWonder** [comment]
I also got the same issue... The upload logic works fine for some controllers but doesn't for others.

**Comment by corexz** [comment]
Hello 
this issue happen to me also , but i figure out that, In my case i was adding same information twice in two different language type in two different database id.
so the file was already moved from tmp/upload folder when the second record id try to access the file.
i manage this by adding` preservingOriginal()` to the first record id accessing the file
`$user_en->addMedia($strorage_path)->preservingOriginal() ->toMediaCollection('posts');`
then i removed it from the second record id 
`$user_lang->addMedia($strorage_path)->toMediaCollection('posts');`

what i do was try to preserve the file in temp/uploads while the adding sequence still in progress. then remove it in the last record insertion.

that is because FileAdder class still accessing the file information when you move files from temp to media collection

**Comment by jinseokoh** [comment]
I'm using Laravel 7.11 w/ PHP 7.4.5. The following code gives me an error like `The file "/tmp/phpcCjOmG" does not exist` when using `FormRequest` but, works fine with `Illuminate\Http\Request`.

```
$model->addMedia($request->file('image'))
            ->toMediaCollection();
```

**Comment by MuhammadSulman** [comment]
@jinseokoh Man, you are right, it works, but I don't know how, if you have any reason about it then please share it.

**Comment by jojomak13** [comment]
@jinseokoh  thanks for that it works fine after using the native `request` not the `formRequest`

**Comment by eskiesirius** [comment]
I am getting this issue.. changing addMediaFromRequest to addMedia didn't work.. im using windows

**Comment by akhzarjaved** [comment]
> I'm using Laravel 7.11 w/ PHP 7.4.5. The following code gives me an error like `The file "/tmp/phpcCjOmG" does not exist` when using `FormRequest` but, works fine with `Illuminate\Http\Request`.
> 
> ```
> $model->addMedia($request->file('image'))
>             ->toMediaCollection();
> ```

Facing same issue. Using version **10.3.4**
well i have used `addMediaFromRequest('file-name')` and it seems to be working fine.

**Comment by igitonga** [comment]
> preservingOriginal()

I did this `$user->addMediaFromRequest("avatar")->preservingOriginal()->toMediaCollection('avatar');` yes it solved the issue but i would find the same media being uploaded twice.

**Comment by Ochieng424** [comment]
> > preservingOriginal()
> 
> I did this `$user->addMediaFromRequest("avatar")->preservingOriginal()->toMediaCollection('avatar');` yes it solved the issue but i would find the same media being uploaded twice.

Did you find a fix for the duplicate uploads? I am facing the same issue as well

**Comment by igitonga** [comment]
> > > preservingOriginal()
> > 
> > 
> > I did this `$user->addMediaFromRequest("avatar")->preservingOriginal()->toMediaCollection('avatar');` yes it solved the issue but i would find the same media being uploaded twice.
> 
> Did you find a fix for the duplicate uploads? I am facing the same issue as well

Yeah i omitted preservingOriginal()
