### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by jcalonso** [spatie/laravel-medialibrary#1646]
Hello!,

I am having a `Serialization of 'Closure' is not allowed` exception when calling the `getFirstMediaUrl` method on a model that is saved in the session,

### Example:

Route:
```
<?php

use App\Post;

Route::get('/', function () {
    $post = new Post();
    session(['post' => $post]);
    session('post')->getFirstMediaUrl('avatar');

    return view('welcome');
});
```

Model:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Post extends Model implements HasMedia
{
    use HasMediaTrait;

    public function registerMediaCollections()
    {
        $this->addMediaCollection('avatar')->singleFile();
    }
}
```

Laravel 6.6.0
Laravel medialibrary 7.14.2
Php 7.3.12

Flareapp link: https://flareapp.io/share/bP9kQZ5Q#F31

Any ideas why this is happening and how to avoid it?

Thanks

**Comment by 4unkur** [comment]
I am having the same issue. Issue happens in Notification class, which is queued

`App\User` class implements `HasMedia`, uses `HasMediaTrait` and has 2 getters:  
```php
    public function getAvatarImageAttribute()
    {
        return $this->getFirstMediaUrl(static::COLLECTION_AVATAR, static::CONVERSION_SMALL);
    }

    public function getAvatarImageThumbAttribute()
    {
        return $this->getFirstMediaUrl(static::COLLECTION_AVATAR, static::CONVERSION_THUMB);
    }
```

Sending a notification is done in `SendExpirationNotifications` job class (which is also queued):
```php
$user->notify(new \App\Notifications\EssentialEmail\NotYetActivated($user));
```

Notification class itself:
```php
class NotYetActivated extends BaseNotification
{
    use Queueable;

    public $activationLink;

    public function __construct(User $user)
    {
        $this->user = $user;
        $this->activationLink = $this->generateActivationLink();

        $this->loadRule();
        $this->setUserId($user->id);
    }
```

This notifications system is working more than 8 months now and I started to get Sentry exceptions once I have deployed recent changes in avatars functionality. Before it was simple Storage::put facade usage and now i used this package (laravel-medialibrary) for image storing/cropping. 

While debugging, I have tried to change 2 getter methods to return a string `'#'` and it fixed the issue. So the reason is in `getFirstMediaUrl` method.

**Comment by 4unkur** [comment]
Just in case someone has similar issues:  
I have applied temp solution. In each notification class where I had `$user` property, I have hid `avatar_image` & `avatar_image_thumb` attributes from $user:  
```php
$user->makeHidden(['avatar_image', 'avatar_image_thumb']);
```
I had edit a lot of files, but it's less painful than to refactor almost whole Notifications functionality on the project.

**Comment by rubenvanassche** [comment]
Okay guys,

So what is going wrong? The PHP `serialize()` function does not allow models to have anonymous functions. In @jcalonso's case the session system of Laravel will try serialize the model which is not possible. In @4unkur's the same thing happens because the notification goes to the queue. You probably should add the SerializesModels trait into your notification, check: https://laravel.com/docs/5.7/queues#class-structure. @jcalonso I don't think you should put your model into a session, because as soon as there is one anonymous function within your model the serialization will break. Hopefully that will help, if you have any questions feel free to ask, I will close this issue for now.

**Comment by jcalonso** [comment]
you are right, thanks, I will refactor the code :+1:
