### ISSUE TITLE
Add authentication to retreive files from webdav

### ISSUE THREAD

**Issue by RosiersRobin** [spatie/laravel-medialibrary#1671]
### Add authentication to retreive files from webdav

I'm trying to have an protected WebDav storage (stackstorage.com) to be accessable. You can access objects via an URL like: `https://rallypodium.stackstorage.com/remote.php/webdav/staging/1/mountain-1244132_960_720.jpg`, however, you need HTTP authentication.

My question is, how can I retrieve the files with a HTTP basic auth?

I currently have a class `WebdavUrlGenerator`, which should generate those URL's, but I have no clue on where to set the header for the request?

|    Q        |   A
|------------ | ------
| Version     | ^7.0.0

**Comment by apocalyarts** [comment]
+1

I also want to have my uploaded images only visible for authenticated users.

- Specify a different disk during upload? CHECK!
- Write my own UrlGenerator? CHECK!

The UrlGenerator will now simply return this in ```getUrl()```:

``` return $this->conversion ? route('mediaItems.show', ['mediaItem' => $this->media, 'conversion' => $this->conversion->getName()]) :  route('mediaItems.show', $this->media);``` 

In my controller I perform my auth check and return the $media object, which defaults to the raw image data via its ```toResponse()``` method.

This should help you @RosiersRobin, solve your problem, but it leaves you with the following issue:

```toResponse()``` always returns the default image. With my URLGenerator I am passing the conversion name as a parameter, so I can access it via ```request->input('conversion', null)``` but there is no way to specify that I want to load the raw image data from a conversion instead of the default image.

**Comment by apocalyarts** [comment]
I'll lust leave my controller code here. Maybe it will help you @RosiersRobin. The controller performs an auth check and afterwards returns the image or one of its conversions (or a placeholder image if no conversion is available):

````
<?php namespace App\Http\Controllers;

use Spatie\MediaLibrary\Models\Media;
use Illuminate\Support\Facades\Request;

class MediaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function show(Media $mediaItem)
    {
        $this->authorize('view', $mediaItem->model);
        if($conversion = Request::input('conversion', null)){
            return $mediaItem->hasGeneratedConversion($conversion) ? response()->file($mediaItem->getPath($conversion)) : redirect(asset('img/img.png')); 
        }
        return $mediaItem;
    }
}
````

**Comment by RosiersRobin** [comment]
The issue I have is not that I just want to display the images to authenticated users on my application side.

The issue is that I'm using a WEBDAV storage to store my files on, which is accessable, but ONLY with credentials. I can not just ask the public link from the image and shot it, I need to authenticate.

But I solved my issue bu fetching the image data, converting it to base64 and spitting out that string to my view.

**Comment by Shohan494** [comment]
any way to use authentication/authorization for this library, basically the image/media url/content? Facing a lot of issues regarding this thing.
