### ISSUE TITLE
addMediaFromBase64 does not save the image with the file extension. Is that correct?

### ISSUE THREAD

**Issue by otavio-araujo** [spatie/laravel-medialibrary#1733]
Im usig Slim Crop Image plugin to cut ande resize the image on the frontend and then when submit, the image is sent to controller like base64.

The "problem" is that when it's saved with addMediaFromBase64 its not puting the file extension together for the original and the responsive-conversions.

![image](https://user-images.githubusercontent.com/30505243/74487087-633d1180-4e9d-11ea-9bdc-2c4fc75ef4af.png)

Is that ok? 

Or am i missing something?

**Comment by izshreyansh** [comment]
You can do something like this:
```
$this->addMediaFromBase64($base64code)
                ->usingFileName(str_random().'.png')
                ->toMediaCollection();
```

**Comment by joeyrush** [comment]
Sorry to bump a closed issue but I have a similar setup to the OP where I'm using the `addMediaFromBase64` method quite a lot and I've noticed that if you don't use the trick that @izshreyansh suggests, then you cannot use `->keepOriginalImageFormat()` in your conversions. It will always convert to JPEG as presumably that method is relying on the filename rather than the metadata.
