### ISSUE TITLE
Is it possible to avoid APP_URL Dependency?

### ISSUE THREAD

**Issue by takielias** [spatie/laravel-medialibrary#1890]
Is it possible to avoid APP_URL Dependency? I want to keep APP_URL value as default http://localhost.

**Comment by freekmurze** [comment]
You can set the APP_URL to whatever you want.

Maybe I don't understand what you mean. In that case, send a PR with the change you are proposing.

**Comment by takielias** [comment]
Without defining APP_URL we can't get the correct media URL.  That is why I want to know Is it possible to make this library working without APP_URL Dependency in .env file?

**Comment by stefanofinetti** [comment]
Sorry to resume and old issue, but I'm facing a situation very similar to the OP.
Basically, I have a laravel installation which covers multiple domains (with a middleware), thus rendering completely useless the APP_URL variable. More, the variable should not be used because url will never have what is in APP_URL value. I've already done some override to the UrlGenerator, but it seems I can't get past use of APP_URL value for getFirstMedia() method, which I'm using to generate responsive <img srcset>. I can't find where APP_URL is read so I can't do another override unless you point me to where I should look. Thanks
