### ISSUE TITLE
uploading files with plus + in the name has incorrect url encoding on s3

### ISSUE THREAD

**Issue by patrickomeara** [spatie/laravel-medialibrary#2194]
Hi team,

Uploading this file using local filesystem works fine however uploading it to s3 has the wrong encoding, where `Major+Maint+1-14+09-30-21.pdf` is persisted in the media table but s3 stores it as `Major%2BMaint%2B1-14%2B09-30-21.pdf`

[Major+Maint+1-14+09-30-21.pdf](https://github.com/spatie/laravel-medialibrary/files/5570906/Major%2BMaint%2B1-14%2B09-30-21.pdf)

AWS recommend handling plus as a special character and url encoding it. https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html See `Characters that might require special handling`

I _can_ handle this but it seems like it _should_ be handled by medialibrary as it works in development using the local filesystem but has a different outcome in production on s3. Maybe it's deeper than this package and should be handled in flysystem.

I would like to start some discussion on this. url encoding and sanitisation is the main reason I moved to medialibrary from my own hand rolled solution. 😄

**Comment by freekmurze** [comment]
My first thought is that it should be handled in FlySystem.

Since there are no other users complaining about this, it seems not a widespread issue.

I currently have no time to investigate this further, but if needed feel free to submit a non-breaking PR that fixes this for you. Make sure to include tests.
