### ISSUE TITLE
[Suggest] Laravel 4 support

### ISSUE THREAD

**Issue by folkevil** [spatie/laravel-medialibrary#23]
Hi,
i know people are switching to L5 but i think L4 still being used in many project. And with any CMS media management is an important part. So, can you make this package to work with L4 ? Thank you.

**Comment by freekmurze** [comment]
Hi, 

Lots of L5 specific functions are being used. Porting this package would take a considerable amount of time. Support for L4 would make the codebase more complicated than it needs to be.

Because we don't need it ourselves, building and maintaining a L4 specific version isn't a priority for us. So don't hold your breath for L4 support.

**Comment by folkevil** [comment]
Thank for your reply. i think i will port a 4.2 version of this package if you agree.

**Comment by freekmurze** [comment]
Yeah sure! I think people on L4.2 will be very grateful for your work.
