### ISSUE TITLE
Bad type annotations on `addMultipleMediaFromRequest`

### ISSUE THREAD

**Issue by jakewtaylor** [spatie/laravel-medialibrary#2388]
Hey, thanks for this library, super helpful!

I've noticed an issue with the `addMultipleMediaFromRequest` method on `InteractsWithMedia`, it returns a Collection but the PHPDoc specifies the return as an array of `FileAdder`, which makes sense, but trying to chain collection methods on to the end of that call causes intellisense to complain that it's not valid.

![image](https://user-images.githubusercontent.com/8126758/114382272-1aa5e480-9b84-11eb-8321-188f768ab51d.png)

I've noticed the `addAllMediaFromRequest` method has the same PHPDoc annotation, but also has a PHP typehint, and that seems to be fine, so I think the solution is to just add the typehint to the method?

**Comment by nikitabuida** [comment]
Still have the same issue even with return type Collection.

in InteractsWithMedia class method addAllMediaFromRequest is annotated with

* @return Spatie\MediaLibrary\MediaCollections\FileAdder[]

So Intelephense is confused (error 1006) because of it. If I remove comment about return type from InteractsWithMedia then the error is gone. 

Should it be 
* @return Collection
instead of 
* @return Spatie\MediaLibrary\MediaCollections\FileAdder[]
?
