### ISSUE TITLE
[feature-request] Disable public path enforcement

### ISSUE THREAD

**Issue by kmbt** [spatie/laravel-medialibrary#247]
Hi, I would like to ask for a possibility to disable the path enforcement mentioned in #190. I believe that while checking the path helps to avoid some mistakes, it makes developing some type of web apps harder.

I am developing a website where access to the media must be protected by login, so I need to store media outside the public root in order to prevent link sharing. The files are sent to the browser through PHP.

If the plugin forces me to put the media directory (or link) in public root, I must take additional precautions to configure the server not to allow file downloads from the directory which makes application maintenance harder.

Would it be possible to implement a configuration option to override the check?

**Comment by kmbt** [comment]
Oh, never mind my request. I have just realized that the check is done in URL generator and not in the Path generator so I just need to write my own URL generator and everything should be ok.

**Comment by sebastiandedeyne** [comment]
> the plugin forces me to put the media directory (or link) in public root

You can store your media anywhere you want, however, if it's not in the public path you'll need to implement the retrieval of the media yourself by writing your own `UrlGenerator` class.

Some resources:

- This issue is on a similar setup: #244 
- Writing your own `UrlGenerator`: https://docs.spatie.be/laravel-medialibrary/v4/advanced-usage/generating-custom-urls

**Comment by kmbt** [comment]
Thank you for the prompt response and for the links :)
