### ISSUE TITLE
Adding media from remote disk with `preservingOriginal()` still removes file.

### ISSUE THREAD

**Issue by ChristianPavilonis** [spatie/laravel-medialibrary#2695]
When adding media from my s3 bucket and using the `preservingOriginal()` method the original file was still removed.

Note this bug still happens in testing when using `Storage::fake('s3')`

 ```
Storage::disk('s3')->exists('/path/to/file');
// true

$yourModel
   ->addMediaFromDisk('/path/to/file', 's3')
    ->preservingOriginal()
   ->toMediaCollection();

Storage::disk('s3')->exists('/path/to/file');
// now false
```

version: 9.10.0

**Comment by freekmurze** [comment]
@cole-flexsim @jon-sm Could you take a look at this?

**Comment by cole-flexsim** [comment]
@freekmurze  Yeah this seems to be because of my recent pull request. https://github.com/spatie/laravel-medialibrary/pull/2638

I'm not taking into account preservingOriginal when I added the $storage->move functionality in src/MediaCollections/Filesystem.php line 65. I believe a quick fix would be to update that line to be $storage->copy instead because there are other places in the code that handle removing the old file during a move. 

That change does partially negate the performance boost that my pull request provided for moving files within the same disk. 

If we want to fix the bug now that's fine and I can go back and look at a more robust way to improve performance later when I have more time

**Comment by freekmurze** [comment]
I'd accept a PR that fixes the bug now. If you don't have the time, I'll just revert the previous PRs tomorrow. 

We can indeed look later at how we could improve performance.

**Comment by cole-flexsim** [comment]
@freekmurze lets just revert the PRs and I'll make a new implementation that will take these issues into account

@ChristianPavilonis if you have time to make a test PR that will test that preservingOriginal() will work when transferring a file to the same disk and transferring a file to a different disk that would be much appreciated

**Comment by freekmurze** [comment]
I've reverted the original PR.
