### ISSUE TITLE
v9.10.0 is not applying CustomHeaders on S3 for original file

### ISSUE THREAD

**Issue by lion2486** [spatie/laravel-medialibrary#2696]
Hello there, yesterday updated to version 9.10 and I figured out that the original file on S3 does not have the custom headers I am passing (ACL => public-read in my case). The Preview & thumb files do have the headers. 
I figured out that the $storage->move() (src/MediaCollections/Filesystem.php:65) does not apply the custom headers to the destination file.
An easy fix could be to undo this improvement, or @cole-flexsim can help figure a better solution on that.
Same also on v9.10.1 
Thank you.

**Comment by cole-flexsim** [comment]
@lion2486 we have been discussing another issue that popped up because of those changes here: https://github.com/spatie/laravel-medialibrary/issues/2695 I believe we are going to revert the changes and then I can go back and figure out a better implementation later.

If you are willing a PR that adds tests to the package that will check that the headers are being passed for different disk and same disk operations that would help me out a lot when I submit the new PR (see https://github.com/spatie/laravel-medialibrary/issues/2695#issuecomment-993652838)

**Comment by freekmurze** [comment]
I've reverted the original PR in the latest release.
