### ISSUE TITLE
Conversions not working with webp

### ISSUE THREAD

**Issue by taliptako** [spatie/laravel-medialibrary#273]
When i try to add media with webp extension conversions not working with jpeg image its working.
Why i cant use webp extension with conversion i wanna use webp extension because its more opimized then jpeg..

**Comment by freekmurze** [comment]
I haven't worked with webp myself and there was nobody asking to support it, that's why it's currently not in the package. 

I'd accept a PR that adds webp compatibilty to the package (if it's not too complex). Of course everything should keep working the way it is if the webp extension is not present on the system.

**Comment by freekmurze** [comment]
Closing this for now, reopen if you want to work on the PR and want to discuss it further.
