### ISSUE TITLE
Many-to-many question

### ISSUE THREAD

**Issue by torkiljohnsen** [spatie/laravel-medialibrary#285]
Have you considered relating many-to-many instead of many-to-one? So using morphToMany instead of morphMany? I have a usecase for that, and I was wondering if I should try your package and overload the `HasMediaTrait` to make this happen. Or will I run into issues immediately?

**Comment by sebastiandedeyne** [comment]
I don't think there's a right answer between the two, and in this case I prefer one-to-many over many-to-many because it vastly reduces complexity (not just the queries, but also when determining what file to delete, which conversions should be available etc.)

In a previous issue, I recommended creating an application-specific pivot model between the media item and your own models if you want n:m relations.

https://github.com/spatie/laravel-medialibrary/issues/205

**Comment by torkiljohnsen** [comment]
For reference to other readers: https://github.com/spatie/laravel-medialibrary/issues/205
