### ISSUE TITLE
Adding a custom directory structure

### ISSUE THREAD

**Issue by loranger** [spatie/laravel-medialibrary#286]
Hello,

As my media folder grows, I'd like to (lately) add a custom path generator.

I'd like to know if there is a good practice in order to achieve this while the app is running and whitout losing any file ?

It seems quite hard, don't you think ?

**Comment by sebastiandedeyne** [comment]
Hmm sorry, don't think I'll be able to give too many useful insights.

I'd write some sort of migration script (either in bash or in php) that would move the media accordingly. Depending on the size of your media folder, it shouldn't take *too* long since moving files on a local file system goes relatively fast.

**Comment by loranger** [comment]
That's the answer I was afraid of ;p

Thank you, anyway !
