### ISSUE TITLE
[Question] Is the tmp folder emptied at some point?

### ISSUE THREAD

**Issue by jpmurray** [spatie/laravel-medialibrary#314]
Ok, this is magic. I'm not entirely awake at this moment, but I have an implementation of Summernote on which some people can add inline images. So far, so good. I was planning to implement Media Library with it at some point, but didn't have time yet. Anyway, one of my user just tried to add an image within summernote and saved it's article and...

The image was saved to the `tmp` directory! Now, I might have started to implement the media library feature in the past, but I don't remember it. That being said, I don't really mind that inlines images of summernote gets saved to tmp directory, it's just easier that way for the moment.

So, questions is: is this directory emptied automatically at some point? If it is, I have to act quick ;-)

**Comment by nicolasbeauvais** [comment]
Maybe this can help you (I don't know which distribution you are using):
http://askubuntu.com/questions/20783/how-is-the-tmp-directory-cleaned-up

Also changing the way media are stored is really easy with this library,  you just have to update your configuration file:
https://docs.spatie.be/laravel-medialibrary/v4/installation-setup-in-laravel

**Comment by jpmurray** [comment]
@nicolasbeauvais Actually, the files are stored in a `media/tmp` directory, the `media` one being where spatie/laravel-medialibrary stores it's own files. I thought this would be a tmp folder created by the package, and not by the system?

**Comment by nicolasbeauvais** [comment]
Can you show me a row of the media table in your database?  Also which
version of the library are you using?

**Comment by jpmurray** [comment]
I'm on 4.8.3. And here's a screenshot of some rows!
<img width="939" alt="screen shot 2016-08-29 at 09 16 20" src="https://cloud.githubusercontent.com/assets/1550428/18052614/55987848-6dc9-11e6-9f49-0fb3e89b8206.png">

**Comment by nicolasbeauvais** [comment]
Everything looks fine,  the version before 4.8.3 add a file path bug which is why I asked,  you are using the media disk which by default if you follow the installation setup https://docs.spatie.be/laravel-medialibrary/v4/installation-setup-in-laravel should write the media's in the `public/media` directory,  the tmp directory should only be used by the package to perform the conversion not to store files.

Can you check your public directory and the media configuration as explained in the installation documentation I linked?
