### ISSUE TITLE
input SubDirectory 

### ISSUE THREAD

**Issue by PeterDeHaberkorn** [spatie/laravel-medialibrary#33]
the ability to pack the files into subfolders does not exist

https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMediaTrait.php#L66

https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem.php#L36

https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem.php#L38

https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem.php#L50

**Comment by freekmurze** [comment]
I don't know what you are trying to say. Could you please describe the problem or feature request?

**Comment by PeterDeHaberkorn** [comment]
sorry, what I meant is that the currently mediafiles stores on a random location 

" / media / { someNumber } / file"

but what I would like to see is the option to set a fixed folder like:

media/{Customer}/{year}/{filetype}

with this function from the model:

public function addMedia($file, $collectionName = 'default', $removeOriginal = true, $addAsTemporary = false, **$subDirectory = ''**)

**Comment by freekmurze** [comment]
I believe this is a very specific use case that many users of the package don't need. Adding it would make the code more complicated than it needs to be. I'm not going to included this.

I'm assuming you are asking for this because you want to use an url like "http://yourdomain.com/media/customer/2014/jpg". You could make a controller that responds to such urls and queries the media table directly.

**Comment by PeterDeHaberkorn** [comment]
No. That was not my intention

My intention was to have a better overview and not for every file and his conversions a folder
