### ISSUE TITLE
Preview On Collection - S3 - URGENT

### ISSUE THREAD

**Issue by beneyraheem** [spatie/laravel-medialibrary#3714]
```
<livewire:media-library collection="test" :model="$test" wire:model="photo" max-items="1" rules="mimes:jpg,jpeg,png|max:6144" />
```

Photo is uploaded to S3, when displaying collection, preview is not loading.

I couldn't find relating this on PRO documents.

**Comment by timvandijck** [comment]
Hey @beneyraheem, I'm sorry you are experiencing trouble.

Due to a limitation in Livewire the collection Livewire plugin does not support uploading multiple files directly to S3: https://spatie.be/docs/laravel-medialibrary-pro/v6/livewire/attachments

I would recommend trying to use the component in "attachment"-mode (without the collection attribute) like this: https://spatie.be/docs/laravel-medialibrary-pro/v6/livewire/attachments
