### ISSUE TITLE
clearMediaCollection rmdir(): Directory not empty

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-medialibrary#397]
so I am trying to clear a media collection:
```
$settings->clearMediaCollection('main_header_logo');
```
but it thorws me this error:

```
rmdir(mypath\media\2016\11\13\92): Directory not empty
```
I am using a custom path generator not sure if it has something to do with not being able to clear a media collection

**Comment by freekmurze** [comment]
The tests [seem to prove](https://github.com/spatie/laravel-medialibrary/blob/8c862e270d49e8bbff6f0993900c8bb59ea165ea/tests/Commands/ClearCommandTest.php) that clearing a media collection does remove the files.

So I'm thinking your issue is caused by the permission on your machine or with your custom pathgenerator.

**Comment by kickthemooon** [comment]
not sure how and why but now its working, change the a bit around and its ok now.
