### ISSUE TITLE
getUrl in Model relation

### ISSUE THREAD

**Issue by mohammad6006** [spatie/laravel-medialibrary#402]
I need to get image path as json

I use 
`         $products = Product::with('categories','media')->paginate(15);`

but this display image file name 

how can I use getUrl ?

**Comment by sebastiandedeyne** [comment]
How exactly are you trying to retrieve the url from the media item?

**Comment by mohammad6006** [comment]
using this code:
![download 9](https://cloud.githubusercontent.com/assets/553379/20597559/acec91a4-b259-11e6-8411-ea8295029438.png)

but I need media image file url or path instead of file name

**Comment by sebastiandedeyne** [comment]
Since `getUrl` is a method—not a property—on the `Media` model, it won't automatically be appended when serializing the media model to json.

To solve this issue, you could either:

- Use an external package to handle your model serialization (which is what I'd recommend)
- Extend the `Media` model, and add the url to `$appends`

Example of an extended `Media` model:

```php
// config/laravel-medialibrary.php

return [
    'media_model' => App\Media::class,
];
```

```php
// app/Media.php

namespace App;

use Spatie\MediaLibrary\Media as BaseMedia;

class Media extends BaseMedia
{
    protected $appends = ['url'];

    public function getUrlAttribute(): string
    {
        return $this->getUrl();
    }
}
```

If you're interested in more advanced model serialization, check out our laravel-fractal package: https://github.com/spatie/laravel-fractal

**Comment by smakman** [comment]
You could also append the image URL to your Product model:

```php
// app/Product.php

namespace App;

...

class Product extends Model
{
    protected $appends = ['image_url'];

    public function getImageUrlAttribute()
    {
        return $this->getFirstMediaUrl('images');
    }
}
```
