### ISSUE TITLE
v5 discussion thread

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-medialibrary#492]
@nicolasbeauvais @sebastiandedeyne 

`v5` of the package is nearing completation and I'm planning to tag it early next week. Do you have any feature requests or suggestions? Breaking changes obviously allowed.

**Comment by nicolasbeauvais** [comment]
Here's my Trello column about media library potential features:

#### Possibility to use the same media multiple amounts of time but with only one upload/conversion.
=> use case: When a user is created I attach a default avatar image to it, when my website will get 1000 users I will have 1000 time the same image + conversions. I can hard link the avatar to avoid that but it's easier if all my code (custom avatar or not) use the same API.

#### New "URL" media type
=> use case: A user can have a media gallery with images/videos, a video can be a .mp4 or a youtube / Vimeo link, always to use a single API instead of having to write some custom code to handle URLs. + It can be a good way to deal with larger files that are already hosted, I don't my users to upload a 2gb video, but I don't mind them using one in their gallery if they have hosted it. We would be able to create custom image generator, for youtube it would be an API call that gets the thumbnail of the video and convert it.

#### Vuejs image loader
=> use case: When a user change it's avatar, we can't display it for like 3-5 seconds until it get converted. The vuejs module could operate in two mode, one that request the image every second until it works or one that wait for a web socket event triggered by a `ConversionHasBeenCompleted`. This is clearly outside of this package scope but it was in my list ^^

**Comment by freekmurze** [comment]
Thanks for your suggestions!

> Possibility to use the same media multiple amounts of time but with only one upload/conversion.
I think this should be handled in application logic. What we do in our project is to just use a presenter that tries to get avatar of a user. If the use has none an url to a generic image is returned. Imho there's no need to store a generic image for each user.

> New "URL" media type
I very much like this idea. Have you any thoughts on how to implement it best? If the implentation is simple, I'd like to add it.

> Vuejs image loader
Yea, like you already mentioned, clearly something that should be handled outside of this package.

**Comment by nicolasbeauvais** [comment]
Also, we can remove image types (except the `TYPE_OTHER` maybe ?):
https://github.com/spatie/laravel-medialibrary/blob/master/src/Media.php#L21-L24

As all type corresponding to an image generator no longer use them:
https://github.com/spatie/laravel-medialibrary/blob/master/src/ImageGenerators/BaseGenerator.php#L44

For the URL feature:
On first tough, I would make an `addUrlMedia` (but with a better name that avoids confusion with the existing `addMediaFromUrl`), use the `file_name` table column to store the URL (that should maybe be renamed to `media_name'? and find a way to detect that a media is a URL so it doesn't go trough the UrlGenerator, could be the `media` column set to `web` but It could break if somebody use a media with that name, or a new `is_url` boolean, or just a string check on the `file_name` to detect if it start with `https?://`

**Comment by sebastiandedeyne** [comment]
> Possibility to use the same media multiple amounts of time but with only one upload/conversion.

Is now the time to look into removing the 1:n relationship in favor of an n:m?

**Comment by freekmurze** [comment]
@sebastiandedeyne Although there is certainly value in having the functionality, we ourselves are probably not going to need it. I'll hold off on this for now because it'll add considerable complexity to the package and I'd like to keep things simple.

Maybe the n:m functionality could live in it's own package.

**Comment by freekmurze** [comment]
@nicolasbeauvais for the url feature, I'm thinking this could be added in a non breaking way, so I'm not going to wait on it before releasing `v5`. I would most certainly accept a PR that adds that functionality in a simple way.

**Comment by freekmurze** [comment]
Boom, released! 🎉  Thanks all for your valuable input. 

Looking forward on working on the improved codebase
