### ISSUE TITLE
Exposing a medias ID, is there a better solution?

### ISSUE THREAD

**Issue by ahjorth** [spatie/laravel-medialibrary#545]
## The problem
I was thinking about some scenarios using this package that could be problematic. Imagine you have `thumb` conversion for most if not all of your collections.

À visitor would find it difficult to locate all the original images by `/images/upload/1/filename.jpg` because just replacing the id `1` with `2` would fail because the filename would be different (probably).

But if he assumes there is a thumb conversion, he could just do `/images/upload/2/conversions/thumb.jpg` and that WOULD produce a thumbnail of the image.

So one of the reason why this could be bad is, say you have a news post that is unpublished. you wouldn't want a user to just be able to fetch every image on your app using this package.

## How I've avoided this
So I've been using the suggested `return md5($media->id).'/';` for my `getPath()` method in my custom `PathGenerator`

I even took it a step further by adding a salt
`return md5($media->id . 'j38akAkjal').'/';`

Now this method does make it hard for someone to iterate through the media on my app.

**But there's a problem** One thing that I've noticed is the Clean command is very reliant on the folder name being the ID. In fact it will not work at all if you use a custom path generator.

My biggest issue with this is how the file looks. MD5 is long and obnoxious and just looks weird if people were to link your images.

Another drawback is the obvious performance hit when you are forced to hash every request to the image path, be it saving the image or displaying them. How large of a performance drain this is I'm not sure, but this leads me to my original question

## Can ID obfuscation be done better?
Is there some way we can decouple the packages reliance on ID?

One solution might be to have a config option to enable obfuscation? If a hash is to be used, maybe salt with the app key?

**What I wish** is maybe a fusion between laravel-medialibrary and laravel-glide, but that might go away from the whole idea behind this package :)

Sorry if I'm not being clear, I'm just very tired. Basically this is just some thoughts I had while I was working on my app - and maybe someone will agree. Or not, that's fine too :)

**Comment by freekmurze** [comment]
Hi, 

thanks for your explaining your thoughts on this in detail.

I'm going to leave the current folder naming (using the media id) as it currently is. I believe that most people have no problem with this. If you want to obfuscate the id, I think you should, like you mentioned, a custom path generator.  I don't think calls to `md5` should pose a significant drop in performance.

I'd take keep this package as simple as it can be, that's why I won't introduce and option that does this out of the box.

@AlexVanderbist Could you take a look if the clean command correctly works when using a custom path generator?
