### ISSUE TITLE
addMedia problem

### ISSUE THREAD

**Issue by dmitry-udod** [spatie/laravel-medialibrary#56]
Hello,

I try to add media to my model like this
```
$path = base_path('resources/uploads');
$fileName = uniqid('client_logo_') . '.' . $logo->getClientOriginalExtension();
$logo->move($path, $fileName);
$client->addMedia($path . DIRECTORY_SEPARATOR . $fileName)->preservingOriginal()->toCollection('clients');
```
But got the error
```
Not null violation: 7 ERROR: null value in column "model_id" violates not-null constraint (SQL: insert into "media" ("name", "file_name", "disk", "collection_name", "size", "custom_properties", "manipulations", "updated_at", "created_at") values (client_logo_55e6baae7ac9c, client_logo_55e6baae7ac9c.png, media, clients, 192991, [], [], 2015-09-02 09:00:30, 2015-09-02 09:00:30) returning "id")
```

Could you please check?

Best Regards 
Dmitry

**Comment by freekmurze** [comment]
Hi, could you check which version you have pulled in? Version 3.2.1 has a bug that causes this problem. It is fixed in 3.2.2.

I you just started out using this package you should:
- delete the media table in your db
- remove the media table migration
- update the package to 3.2.2
- publish the migration
- run the migration

If you already have contents in your media table and it's not possible to start over you should make the model_id and model_type nullable.

I'm sorry for this hassle. It's my mistake and I'll try to make sure it won't happen again.

Let me know if this fixes your problem.

**Comment by dmitry-udod** [comment]
You are man! :)

Everything is OK.

Thank a lot

**Comment by uyab** [comment]
Hi @freekmurze, I'm sorry if my previous PR caused this problem. But it looks like the root problem is on this line: https://github.com/spatie/laravel-medialibrary/blob/master/src/FileAdder/FileAdder.php#L270-L272

The first `save()` is unnecessary and should be removed. This is the 'usual' way to insert related model in Laravel. It also produces less query (1 vs 2). I hope you have time to check it out :)

**Comment by freekmurze** [comment]
Yeah, I'll check it in the coming days and put your contributions back in the code.

(no excuses from you necessary, I should have checked it more thoroughly when merging your PR.)

**Comment by freekmurze** [comment]
@uyab I've added your contribution back in. You were correct regarding the root problem. Thanks!

**Comment by uyab** [comment]
Thank you, really like this and the others spatie package.
