### ISSUE TITLE
Apply event in manipulation

### ISSUE THREAD

**Issue by Krato** [spatie/laravel-medialibrary#592]
Hi again.

I'm trying to set a image with and height before make a crop. So I found `apply()` method in [your image package](https://docs.spatie.be/image/v1/usage/advanced-manipulations#the-codeapplycode-method).

But, how can I do using `manipulations`field?

Or how can I set an array manipulations like:
```php
$manipulations = [
    'resized' => [
        ['width' => $imageWidth, 'height' => $imageHeight],
        ['manualCrop' => $imageWidth.', '.$imageHeight.', '.abs($value['imageLeft']).', '.abs($value['imageTop'])],
    ],
];
```

Thanks!

**Comment by AlexVanderbist** [comment]
Hi @Krato 

I don't think it's possible (yet) to use the `apply` method on media specific conversions since it's not really a manipulation in the first place. 

All the `apply` method does is start a new `manipulationSequence` every time it's called. When you're using media specific conversions the entire array you provided will be used as a `manipulationSequence` without checking for `apply`.

I do see the need for different manipulationSequences when using media specific conversions and I think the example you provided would be a nice way to implement that.

Once that's in place another option might be to add a `toArray` method on the `Conversion` class, this way you could create `Conversion`s just like in your `HasMedia` models and add those to the specific media:

```php
$resizedConversion = Conversion::create('resized')
    ->width(123)
    ->apply()
    ->manualCrop(20, 20, 10, 10);

$media->manipulations = [
    'resized' => $resizedConversion->toArray()
];
```

**Comment by freekmurze** [comment]
I'd accept a PR that adds support for multiple media specific manipulationsSequences.

For the easy building of a manipulations array I'd accept PR on `spatie/image` that adds a static `create` method and an `toArray` method on `Manipulations`.

So when can do this:

```php
$resizedConversion = Manipulations::create()
    ->width(123)
    ->apply()
    ->manualCrop(20, 20, 10, 10);

$media->manipulations = [
    'resized' => $resizedConversion->toArray()
];
```

**Comment by Krato** [comment]
Hope I understand.

Now I get it working just modifying manipulations.php fle.

Here is the pull: https://github.com/spatie/image/pull/16

**Comment by JinalSomaiya** [comment]
@freekmurze 

`$resizedConversion = Manipulations::create()
                ->width(123)
                ->apply()
                ->manualCrop(20, 20, 10, 10);
        $media->manipulations = [
            '*' => $resizedConversion->toArray()
        ];

        $media->save();`
I want to crop image and my code is as above.
 it is regenerating conversions but cropping is not working.
