### ISSUE TITLE
Conversions folder not being generated on server?

### ISSUE THREAD

**Issue by aaronfullerton** [spatie/laravel-medialibrary#61]
Hi,

First, thank you for creating this library. It has been really helpful and working well until recently. However, for some reason, the conversions folder is no longer being created on my server. Any thoughts on what might be causing this? The original file is being uploaded properly and calling `getFirstMediaUrl('images', 'thumbnail')` returns the proper url, but the actual conversions folder and the appropriate file do not exist. As far as I'm aware, no errors are being thrown. 

Server permissions on the public folder are 777 and gd is installed.

My model
```php
...
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Listing extends Model implements HasMediaConversions
{

	use HasMediaTrait;

        ...

	public function registerMediaConversions(){
	    $this->addMediaConversion('thumbnail')
	    	->setManipulations(['w' => 150, 'h' => 170])
	    	->performOnCollections('images');
	}
...
}
```

Add the method where the upload is taking place

```php
        if ( $request->hasFile('thumbnail'))  {
            $listing->addMedia($request->file('thumbnail'))->toCollection('images');
        }
```

Thanks for your help!

**Comment by aaronfullerton** [comment]
Whelp. I'm dumb. It was an issue with my queue handler. Thanks!

**Comment by freekmurze** [comment]
I'm glad you found the solution quickly :+1:

**Comment by dfoxxdfoxx** [comment]
I know it is a old issue but i am having a similar problem. Could one of you please tell me how this is fixed?

**Comment by SvetoslavStefanov** [comment]
Thanks a lot to SoboLAN for sharing this, it helped me, although I had a little bit different problem.
First in 2022 the .env setting is already called QUEUE_CONNECTION, instead of QUEUE_DRIVER.
In my case the "sync" attribute didn't work for some reason, so I changed it to `database`.

To have your queue working with database, you'll need additional table called `jobs`. Create it via the cli: php artisan queue:table 
Then you'll need something to actually execute those jobs - put this code into cron job that is executable on every minute (i.e. * * * * * *): php artisan queue:work --stop-when-empty --timeout=300
NOTE: you might need to increase your memory limit to 1024, because 128MBs is not enough to process images these days. In my case I had to add additional parameter `php -d memory_limit=1024M artisan ....`

And last, but not least - your storage folder must have permissions: `chmod 777 storage` - otherwise you wouldn't be able to upload files there.

Although the package is great, thank you devs, a few trown errors would have been a great addition to the package. Otherwise it's shooting in the dark if you're doing the right think and if not what's the problem. Loading a blank page without errors is the worst thing and checking folder's permissions is quit easy operation to do.
