### ISSUE TITLE
[Testing] Update docs to show how library can be mocked

### ISSUE THREAD

**Issue by olimorris** [spatie/laravel-medialibrary#62]
I was watching Jeff Way's [unit testing episode](https://laracasts.com/series/build-project-flyer-with-me/episodes/17) recently and having successfully used this library I wondered how I could mock it in a similar fashion to JW and figured this would be a useful addition to the readme.

In my test I have the following:
```PHP
// As per Jeff's tutorial
$file = m::mock(UploadedFile::class, [
    'getClientOriginalName'      => 'foo.png',
    'getClientOriginalExtension' => 'png'
]);

// Errors get thrown before we even call the AddPhotoToJob class if we don't mock these
$file->shouldReceive('getPath')->once()->andReturn('images/foo.png');
$file->shouldReceive('getFilename')->once()->andReturn('foo.png');
$file->shouldReceive('getMimeType')->once()->andReturn('image/png');

(new AddPhotoToJob($job, $file))->attach();
```
and it returns:
```
1) PhotosTest::it_adds_a_photo_into_storage
Spatie\MediaLibrary\Exceptions\FileDoesNotExist:

/home/vagrant/Code/DevSite/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php:251
/home/vagrant/Code/DevSite/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php:245
/home/vagrant/Code/DevSite/app/Repos/Photos/AddPhotoToJob.php:53
/home/vagrant/Code/DevSite/tests/Integration/PhotosTest.php:32

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```
I have gotten the tests to green by placing a stub in storage and setting the path using ```storage_path``` but of course the library moves the file rendering the next test rerun useless unless I spin up another stub.

**Comment by freekmurze** [comment]
I'm by no means an expert on how to test this (and haven't seen the lesson yet you are referring to). I'm guessing that in the `AddPhotoToJob` does a call to the medialib somewhere. I think you should send that call to a mock instead of sending in to the real medialib. Your tests should only test your own code and not the medialib's.

I don't think that how to mock the medialib should be in the readme of this package. But I'm interested in how you are going to make your test work. Let me know when you've figured it out.
