### ISSUE TITLE
Optimize every image and not only conversions

### ISSUE THREAD

**Issue by Krato** [spatie/laravel-medialibrary#707]
Hi, is there a possibility to call `optimize()` on every image and not only for conversions?

Thats will be greate cause you an optimize all images and then save only the optimized version.

Somthing like:

```
$newsItem
   ->addMedia($pathToFile)
   ->preservingOriginal()
   ->optimize()
   ->toMediaCollection();
```

Thanks

**Comment by freekmurze** [comment]
You can easily optimize any image you want by using the `optimize` method of our image package. More info here: https://docs.spatie.be/image/v1/image-manipulations/optimizing-images

(Under the hood the same package is used by the medialibrary)

**Comment by sebastiandedeyne** [comment]
You wouldn't want to do this either, since the optimizer might be able to do a better job with the converted image than the original. For example, if you're converting an image to jpeg, GD or Imagick will generate a new jpeg, full of cruft that can probably be optimized. The initial optimization will have been in vain. Optimization should happen as late as possible.

**Comment by elshobokshy** [comment]
Is it possible to optimize any image put inside a collection?

```
$this->addMediaCollection('slogan')
    ->accepts('image/*')
    ->singleFile()
            ->optimize(); <--- This throws an error, of course
```

But is there a way to do that? @freekmurze Why does it only work for conversions?

**Comment by freekmurze** [comment]
The main idea behind the medialibrary is that it doesn't touch your original file at all. If you want some kind of optimisation, you'll need to apply it to a file before adding it to the medialibrary.

**Comment by elshobokshy** [comment]
I see, thanks for sharing that info lol, it answers my question :)
