### ISSUE TITLE
Administrating large amount of images

### ISSUE THREAD

**Issue by addorange** [spatie/laravel-medialibrary#843]
As I am currently further tinkering around with the MediaLibrary another question occured: Currently I have an overview of all used images in my medialibrary, grouped by its filenames to prevent showing up a lot of similar images. The usercan pick from these to attach it to another model, which does simply mean to use the picked images original and upload it once again attaching it.

So, there will be another image with same filename within the library. There is no issue with that, unless there may be another image uploaded with an already existing filename, but different content. As the grouped view will not recognize any difference it may occur that different images will be grouped in one row, so the user may possibly not realize older images.

I thought of additional attributes to sort by like size or even custom properties, but it all feels a bit random. Is such a selection with insuring to group only similar images even possible in a reliable way?

Cheers.

**Comment by dafonso** [comment]
@addorange, you have a couple solutions for that. First off you should be using collections to store the uploaded media, that way is easier to distinguish between media for different purposes.

Second, you could use a really fast way to see if an uploaded media already exists in the library.

```php
$mediaItem = $model
    ->addMediaFromRequest('your_form_file_input_name')
    ->withCustomProperties(['md5' => md5_file($request->file('your_form_file_input_name')->getRealPath())])
    ->toMediaCollection();
```

Unfortunately the custom properties on media library isn't a JSON field, otherwise it would make the queries easier. But still you could check for duplicates hacking something on the likes of:

```php
Media::where('custom_properties', 'LIKE', '%'.md5_file($request->file('your_form_file_input_name')->getRealPath()).'%'
```
Change this to fit for a collection if needed...
