### ISSUE TITLE
Generated responsive images bigger than original size?!

### ISSUE THREAD

**Issue by Omranic** [spatie/laravel-medialibrary#890]
Hello, we've experienced this and we're not sure which layer it relates to, is it something with the package, with the server generation tools, or maybe something fixed though configuration; check screenshots first:
![screenshot_2017-12-31_01_40_09](https://user-images.githubusercontent.com/406705/34458019-f759df86-edcb-11e7-9a13-3d6dacdf548c.png)
![screenshot_2017-12-31_01_39_58](https://user-images.githubusercontent.com/406705/34458020-f99c1278-edcb-11e7-892d-3c09b71a67ec.png)

As you can see, some of the smaller images (dimensions) are actually bigger in (size), which is strange. The original dimensions is 1920 * 1080 with size of 964.8 KB.

Another question: why responsive generation generate same dimension as original 1920 * 1080 before in addition to all the smaller sizes, as per docs I though it starts at 70% ratio, right?

Any thoughts?

**Comment by freekmurze** [comment]
@brendt could you take a look at this?

Next year is fine 🍾

**Comment by brendt** [comment]
@Omranic before looking into this, do you think it would be possible to share the image? It'll make debugging easier.

**Comment by Omranic** [comment]
@brendt Well, that's unexpected request 😂  but yeah, seems ok! 😏

Not sure if GitHub will upload with same quality/size or not, but here we go:
![screenshot 2017-10-05 21 10 01](https://user-images.githubusercontent.com/406705/34467576-b003ec56-eefe-11e7-9762-c020d5432b86.png)

**Comment by brendt** [comment]
I don't have the code with me now, I'm going to take a look at it starting next week.

**Comment by brendt** [comment]
Did some testing. Turns out the original image was very helpful, as many images don't have this problem.

These are the file sizes of the responsive variations of the original image, in order of size.

![original_test](https://user-images.githubusercontent.com/6905297/34675676-aa08346a-f48a-11e7-8e0f-6412decfda21.png)

I tried out lots of other images, and can see this issue returning in PNG encoded files, with large areas of the same color. An example:

![screen___medialibrary_original_395_246](https://user-images.githubusercontent.com/6905297/34675756-e046a502-f48a-11e7-8c51-8aa2395c55b6.png)

This image (its large variant) produces these filesizes:

![white_image](https://user-images.githubusercontent.com/6905297/34675771-eb8c795a-f48a-11e7-805e-f6a7139c43c8.png)

Encoding the source image as JPEG, and then running it through the media library shows these filesizes, which makes much more sense:

![white_image_jpeg](https://user-images.githubusercontent.com/6905297/34675805-fe7cb71e-f48a-11e7-9b44-b06d39cd8df0.png)

I also tried another kind of image, with lots of the same colors in it:

![screen_black___medialibrary_original_472_295](https://user-images.githubusercontent.com/6905297/34675885-37cfd7a8-f48b-11e7-806e-34e2079eb831.png)

![black_image](https://user-images.githubusercontent.com/6905297/34675858-2274ec18-f48b-11e7-8b63-511a9e3bc3bf.png)

So that's that for my first observations. Going to look into the reason now. It probably has to do something with the optimisers ran on each responsive variation.

**Comment by brendt** [comment]
@willemvb helped reveal the underlying issue. We compared a manually downscaled image in photoshop to the generated image from the medialibrary with kaleidoscope:

<img width="780" alt="screen shot 2018-01-10 at 08 45 34" src="https://user-images.githubusercontent.com/6905297/34761265-5474f920-f5e3-11e7-836c-8162bd0673f1.png">

The interesting part is the white background, which should not differ; but the medialibrary (actually an underlying package) will take that plain white background, and make lots of artifacts. Instead of one color, there's a subtle difference between `#ffffff` and `#fefefe`. I'll be looking into where exactly this "optimisation" happens later this week. It will probably be one of the image optimiser binaries, which we should give an extra parameter to.

**Comment by brendt** [comment]
Update: the problem happens when downscaling images if using `gd`. `imagick` seems to work just fine. I'm looking if there's a way to configure `gd` to fix the issue.

**Comment by brendt** [comment]
Addressing the underlying issue: https://github.com/thephpleague/glide/issues/218

**Comment by Omranic** [comment]
Wow, I respect the efforts given to deep dive into the insights of that issue, kudos 👏

**Comment by brendt** [comment]
We've merged a commit in the v7 branch to solve this, for both the `gd` and `imagick` drivers.

**Comment by robbens** [comment]
I also have the same problem. Tried gd and imagick. 
Both very similar in file size.

Original size: 286 KB
Biggest responsive size: 352 KB

![dell-attore-14](https://user-images.githubusercontent.com/12089594/53092265-47838180-354f-11e9-8b84-8961d33549c9.jpg)

**Comment by brendt** [comment]
Are you using v7 of the media library? If so, please provide an the downscaled image with the larger size, and the original.

**Comment by robbens** [comment]
Yes, I'm using v7.

**Original**
![dell-attore-14](https://user-images.githubusercontent.com/12089594/53093341-1b1d3480-3552-11e9-8f36-44a28093fff1.jpg)

**Downsized**
![dell-attore-14___medialibrary_original_1338_892](https://user-images.githubusercontent.com/12089594/53093327-1193cc80-3552-11e9-90ba-19d31edbd1ac.jpg)

**Comment by brendt** [comment]
As I expected: there are lots of artifacts generated by the underlying glide library..

<img width="705" alt="screen shot 2019-02-20 at 14 01 06" src="https://user-images.githubusercontent.com/6905297/53093555-0754dc80-3518-11e9-831e-4901834ba7e0.png">

The way we solved this issue was by adding extra optimizers to the generated responsive images. This however never solved the underlying problem. I'm afraid that because of the complexity of your image, this optimizer trick isn't good enough to mitigate the real issue.

Unfortunately, the real issue is in a package that's not our own: https://github.com/thephpleague/glide/issues/218

You could try and play around in your local project with optimizer settings, but I'm afraid that's the only help I can give at the moment 😕

**Comment by robbens** [comment]
I see. Thank you so much for your time. I'll definitely post here if I find a good solution 👍

**Comment by robbens** [comment]
Kinda unrelated question. But are the generated responsive images compressed through the various optimization tools? If not; What's a good way to do this?

**Comment by brendt** [comment]
They should be optimised, which was the "fix" for this issue: https://github.com/spatie/laravel-medialibrary/commit/d96ce0e22db7069abf335424be65ed0232c0d135
