### ISSUE TITLE
How to include conversions with getMedia()?

### ISSUE THREAD

**Issue by eminos** [spatie/laravel-medialibrary#892]
I'm using `getMedia()` to return a json response, but how do I include info about the media conversions in that collection?

I can see a "manipulations" property for the media in the returned collection, but that's just an empty array even though I have conversions set up for the model (and I can see the converted file on the filesystem).

**Comment by adiachenko** [comment]
Here you go, buddy. I have encountered the same issue not long ago.

```
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\Resource;
use Spatie\MediaLibrary\Conversion\Conversion;
use Spatie\MediaLibrary\Conversion\ConversionCollection;

class MediaResource extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->resource->id,
            'file_name' => $this->resource->file_name,
            'href' => $this->resource->href,
            'versions' => $this->getVersions(),
        ];
    }

    /**
     * @return mixed
     */
    protected function getVersions()
    {
        $conversions = ConversionCollection::createForMedia($this->resource);

        $versions = $conversions->reduce(function ($carry, Conversion $conversion) {
            if ($conversion->shouldBePerformedOn($this->resource->collection_name)) {
                $name = $conversion->getName();
                $carry[$name] = $this->resource->getFullUrl($name);
            }

            return $carry;
        }, []);

        return array_merge($versions, [
            'original' => $this->resource->getFullUrl()
        ]);
    }
}

```

Overall, I advise avoiding using `getMedia` for API responses. You should write your own relationships for each media collection and eager load it directly instead. See example implementation below.

```
<?php

namespace App;

use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

trait HasMedia
{
    use HasMediaTrait;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function morphOneMedia()
    {
        return $this->morphOne(config('medialibrary.media_model'), 'model')->orderBy('order_column')->limit(1);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function morphManyMedia()
    {
        return $this->morphMany(config('medialibrary.media_model'), 'model')->orderBy('order_column');
    }
}
```


```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\Media;

class Section extends Model implements HasMediaConversions
{
    use HasMedia;

    public const MEDIA_IMAGES = 'images';
    public const MEDIA_BANNER_IMAGES = 'banner_images';

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function image()
    {
        return $this->morphOneMedia()->where('collection_name', static::MEDIA_IMAGES);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function bannerImages()
    {
        return $this->morphManyMedia()->where('collection_name', static::MEDIA_BANNER_IMAGES);
    }
}
```

The package is heavily tailored to the needs of monolithic applications. You are expected to do some customization to make it work for API development workflow. But once it is done, it works perfectly.

**Comment by eminos** [comment]
@adiachenko Thank you! This is very useful.

**Comment by corbin88** [comment]
@adiachenko 

Can you please explain how to implement this? I'm not overly sure what I am overriding and what I'm creating. It would be helpful to gets some comments in the code you provided.

My guess is I create a resource called MediaResource and create my own HasMedia trait in my App folder. 

I'm guessing the "Section" model is just a placeholder for any model? So for example:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\Media;

class User extends Model implements HasMediaConversions
{
    use HasMedia;

    public $with = ['media'];
    
    public const MEDIA_AVATAR_IMAGES = 'avatar';
    

    public function registerMediaCollections()
    {
        $this->addMediaCollection('avatar')->singleFile();

    }


    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('profile_thumbnail')
              ->fit(Manipulations::FIT_CROP, 200, 200)
              ->withResponsiveImages()
              ->performOnCollections('avatar');

        $this->addMediaConversion('thumbnail')
              ->fit(Manipulations::FIT_CROP, 50, 50)
              ->performOnCollections('avatar');
    }
    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function avatar()
    {
        return $this->morphOneMedia()->where('collection_name', static::MEDIA_AVATAR_IMAGES);
    }

}
```
[I'm trying to eager load media with the users model to and get the path there. As my issue states.](https://github.com/spatie/laravel-medialibrary/issues/1388) Would I not need to use some controller method to implement that resource? Instead of `Auth::User()`?

**Comment by adiachenko** [comment]
@corbin88 Yeah, the Section is just a generic model to showcase how you would use the trait. Though the given example is very basic. 

There is more to be done to really shoehorn this lib into JSON API context. For example, by default the lib doesn't scope returned conversions. Say, by convention, you have all image collections in your API called _images_ (product.images, category.images etc.). When trying to get product images conversions, you'll have unrelated category images in your responses because there is no scoping.

[I created a gist with more snippets](https://gist.github.com/adiachenko/508d227ce3ce444aa1e649965a7f157a) on I how managed to work around laravel-medialibrary limitations. Hope it'll give you some ideas. Sorry I can't explain more right now, because I moved on to another project and don't remember all the nitty-gritty details myself. It looks kinda confusing even for me at this point. 😆
