### ISSUE TITLE
Resizing is always sizing up

### ISSUE THREAD

**Issue by jerauf** [spatie/laravel-medialibrary#899]
Is there a way to define max height in the conversion? Photos that are smaller are scaling up to fit the height parameter and I want that to be the maximum.

**Comment by freekmurze** [comment]
Take a look at the `fit` operation to learn all the options: https://docs.spatie.be/image/v1/image-manipulations/resizing-images#fit

**Comment by aghayeff** [comment]
> Take a look at the `fit` operation to learn all the options: https://docs.spatie.be/image/v1/image-manipulations/resizing-images#fit

Fit parameter is always require height. Sometimes we do not know what is the height should be, it could be different depending on photo dimensions.

Due to case using ->width() parameter is good. But, width parameter is always sizing up, as @jerauf mentioned.

Lets say user can upload an image between 500-2000px (width)

But I do not want to display clients big image, I prefer displaying an image max width 1024px

        $this->addMediaConversion('xl')
            ->width(1024)
            ->optimize();
            
 
 Now, if user uploads an image with 500px (width), it will again size up....       
 
 Is is possible, just skipping size up if image with less than 1024px?

**Comment by aghayeff** [comment]
Fit parameter always requires height. Sometimes we do not know what is the height should be, it could be different depending on photo dimensions.

Due to case using ->width() parameter is good. But, width parameter is always sizing up, as @jerauf mentioned.

Lets say user can upload an image between 500-2000px (width)

But I do not want to display clients big image, I prefer displaying an image max width 1024px

    $this->addMediaConversion('xl')
        ->width(1024)
        ->optimize();
Now, if user uploads an image with 500px (width), it will again size up....

Is is possible, just skipping size up if image with less than 1024px?

**Comment by khusan-dev** [comment]
If anyone else has this problem. I did this to create thumbnails. In the arguments, specify the maximum width and height for the photo. If the picture is smaller than the given value the picture will not be resized. If the picture is larger then the picture is resized by a given value, while the aspect ratio of the picture will be saved.

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('large')
            ->fit(Manipulations::FIT_MAX, 1068, 1068);
        $this->addMediaConversion('medium')
            ->fit(Manipulations::FIT_MAX, 696, 696);
        $this->addMediaConversion('small')
            ->fit(Manipulations::FIT_MAX, 300, 300);
    }

**Comment by yaroslavolekh** [comment]
I have the same problem. Any configuration  always goes to upscale smaller images
