### ISSUE TITLE
getMedia() should be type-hinted for an Eloquent Collection

### ISSUE THREAD

**Issue by cviebrock** [spatie/laravel-medialibrary#944]
```php
$media = $post->getMedia();
```

This will return a `\Illuminate\Database\Eloquent\Collection`, but all the code is type-hinted or doc-blocked with `Illuminate\Support\Collection`.

I realize one extends the other, so technically it's correct ... but it means that my IDE complains when I try and do:

```php
$media->modelKeys();
```

Would you consider changing the type-hints?

**Comment by freekmurze** [comment]
I'd accept a PR that changes the return type. All current tests should pass.

**Comment by brendt** [comment]
I tried this out, but don't think it's possible, because `Spatie\MediaLibrary\HasMedia\HasMediaTrait::loadMedia` sometimes returns `Illuminate\Support\Collection` instead of `Illuminate\Database\Eloquent\Collection`.

https://github.com/spatie/laravel-medialibrary/blob/master/src/HasMedia/HasMediaTrait.php#L458-L460

**Comment by freekmurze** [comment]
I guess we'll leave things as they are for now.
